In [113]:
#data cleaning ,
#scaling(normalzation and standardization)
#feature encoding(one-hot and label)
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pylab as plt

In [114]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [115]:
dataset=sns.load_dataset('titanic')

In [116]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [117]:
dataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [118]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [119]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [120]:
dataset["age"] = dataset["age"].fillna(dataset["age"].median())

In [121]:
dataset["embark_town"] = dataset["embark_town"].fillna(dataset["embark_town"].mode()[0])

In [122]:
dataset["embarked"] = dataset["embarked"].fillna(dataset["embarked"].mode()[0])

In [123]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [124]:
scaler1=StandardScaler()
scaler2=MinMaxScaler()

In [125]:
dataset[["age_scale","fare_scale"]]=scaler1.fit_transform(dataset[["age","fare"]])

In [126]:
dataset.tail(20)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_scale,fare_scale
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False,1.355510,0.409741
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True,0.279612,-0.547748
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True,1.355510,-0.467209
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False,-0.104637,-0.165189
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True,-1.103685,-0.502949
876,0,3,male,20.0,0,0,9.8458,S,Third,man,True,NaN,Southampton,no,True,-0.719436,-0.450180
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,-0.796286,-0.489442
878,0,3,male,28.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,-0.104637,-0.489442
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,2.047158,1.025945
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False,-0.335187,-0.124920
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,0.279612,-0.489442
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True,-0.565736,-0.436671
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True,-0.104637,-0.437007
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True,-0.335187,-0.506472
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False,0.740711,-0.061999
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,-0.181487,-0.386671
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,-0.796286,-0.044381
888,0,3,female,28.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,-0.104637,-0.176263
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,-0.258337,-0.044381
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.202762,-0.492378

In [127]:
dataset["age"].mean()

np.float64(29.36158249158249)

In [128]:
dataset["age"].std()

np.float64(13.019696550973201)

In [129]:
from sklearn.preprocessing import LabelEncoder

In [130]:
le=LabelEncoder()

In [ ]:
dataset["embark_label"]=le.fit_transform(dataset["embarked"])

/home/shahidkx07/artificial_i/venv/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ValueError: Columns must be same length as key

In [135]:
dataset[["embarked","embark_label"]]

    embarked  embark_label
0          S             2
1          C             0
2          S             2
3          S             2
4          S             2
..       ...           ...
886        S             2
887        S             2
888        S             2
889        C             0
890        Q             1

[891 rows x 2 columns]