In [33]:
import numpy as np
import pandas as pd
import sklearn

In [34]:
df=pd.read_csv('../datasets/fraud_dataset.csv')

In [35]:
df.head(5)

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,...,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend,Fraud_Label
0,TXN_33553,USER_1834,39.79,POS,2023-08-14 19:30:00,93213.17,Laptop,Sydney,Travel,0,...,7,437.63,3,Amex,65,883.17,Biometric,0.8494,0,0
1,TXN_9427,USER_7875,1.19,Bank Transfer,2023-06-07 04:01:00,75725.25,Mobile,New York,Clothing,0,...,13,478.76,4,Mastercard,186,2203.36,Password,0.0959,0,1
2,TXN_199,USER_2734,28.96,Online,2023-06-20 15:25:00,1588.96,Tablet,Mumbai,Restaurants,0,...,14,50.01,4,Visa,226,1909.29,Biometric,0.8400,0,1
3,TXN_12447,USER_2617,254.32,ATM Withdrawal,2023-12-07 00:31:00,76807.20,Tablet,New York,Clothing,0,...,8,182.48,4,Visa,76,1311.86,OTP,0.7935,0,1
4,TXN_39489,USER_2014,31.28,POS,2023-11-11 23:44:00,92354.66,Mobile,Mumbai,Electronics,0,...,14,328.69,4,Mastercard,140,966.98,Password,0.3819,1,1

In [36]:
df.columns

Index(['Transaction_ID', 'User_ID', 'Transaction_Amount', 'Transaction_Type',
       'Timestamp', 'Account_Balance', 'Device_Type', 'Location',
       'Merchant_Category', 'IP_Address_Flag', 'Previous_Fraudulent_Activity',
       'Daily_Transaction_Count', 'Avg_Transaction_Amount_7d',
       'Failed_Transaction_Count_7d', 'Card_Type', 'Card_Age',
       'Transaction_Distance', 'Authentication_Method', 'Risk_Score',
       'Is_Weekend', 'Fraud_Label'],
      dtype='str')

In [37]:
df = df[['Transaction_Amount', 'Transaction_Type', 'Risk_Score', 'Fraud_Label']]

In [38]:
df = df.drop_duplicates()

In [39]:
df.isna().sum()

Transaction_Amount    0
Transaction_Type      0
Risk_Score            0
Fraud_Label           0
dtype: int64

In [40]:
df

       Transaction_Amount Transaction_Type  Risk_Score  Fraud_Label
0                   39.79              POS      0.8494            0
1                    1.19    Bank Transfer      0.0959            1
2                   28.96           Online      0.8400            1
3                  254.32   ATM Withdrawal      0.7935            1
4                   31.28              POS      0.3819            1
...                   ...              ...         ...          ...
49995               45.05           Online      0.1493            0
49996              126.15              POS      0.3653            1
49997               72.02           Online      0.5195            0
49998               64.89    Bank Transfer      0.7063            1
49999               13.00    Bank Transfer      0.8938            1

[49999 rows x 4 columns]

In [41]:
df

       Transaction_Amount Transaction_Type  Risk_Score  Fraud_Label
0                   39.79              POS      0.8494            0
1                    1.19    Bank Transfer      0.0959            1
2                   28.96           Online      0.8400            1
3                  254.32   ATM Withdrawal      0.7935            1
4                   31.28              POS      0.3819            1
...                   ...              ...         ...          ...
49995               45.05           Online      0.1493            0
49996              126.15              POS      0.3653            1
49997               72.02           Online      0.5195            0
49998               64.89    Bank Transfer      0.7063            1
49999               13.00    Bank Transfer      0.8938            1

[49999 rows x 4 columns]

In [42]:
df = df[['Transaction_Amount', 'Transaction_Type', 'Risk_Score', 'Fraud_Label']]

df = df.dropna()
df = df.drop_duplicates()

In [43]:
df

       Transaction_Amount Transaction_Type  Risk_Score  Fraud_Label
0                   39.79              POS      0.8494            0
1                    1.19    Bank Transfer      0.0959            1
2                   28.96           Online      0.8400            1
3                  254.32   ATM Withdrawal      0.7935            1
4                   31.28              POS      0.3819            1
...                   ...              ...         ...          ...
49995               45.05           Online      0.1493            0
49996              126.15              POS      0.3653            1
49997               72.02           Online      0.5195            0
49998               64.89    Bank Transfer      0.7063            1
49999               13.00    Bank Transfer      0.8938            1

[49999 rows x 4 columns]

In [44]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
df['Transaction_Type'] = LE.fit_transform(df['Transaction_Type'])

In [45]:
X = df[['Transaction_Amount', 'Transaction_Type', 'Risk_Score']]
y = df['Fraud_Label']

In [46]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [48]:
y_pred = model.predict(X_test)
y_pred = np.where(y_pred == -1, 1, 0)

/home/shahidkx07/artificial_i/venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

In [49]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [50]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[4794 1937]
 [2323  946]]
              precision    recall  f1-score   support

           0       0.67      0.71      0.69      6731
           1       0.33      0.29      0.31      3269

    accuracy                           0.57     10000
   macro avg       0.50      0.50      0.50     10000
weighted avg       0.56      0.57      0.57     10000

0.574

In [51]:
print(LE.classes_)

['ATM Withdrawal' 'Bank Transfer' 'Online' 'POS']

In [54]:
new_data = pd.DataFrame({
    'Transaction_Amount': [5000],
    'Transaction_Type': [LE.transform(['Online'])[0]],
    'Risk_Score': [0.8]
})

In [55]:
new_scaled = scaler.transform(new_data)

In [56]:
prediction = model.predict(new_scaled)

/home/shahidkx07/artificial_i/venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

In [57]:
if prediction[0] == -1:
    print("Suspicious Transaction")
else:
    print("Normal Transaction")

Suspicious Transaction