In [98]:
import numpy as np
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [99]:
dataset=sns.load_dataset("titanic")

In [100]:
print(dataset.head(100))

    survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0          0       3    male  22.0      1      0   7.2500        S   Third
1          1       1  female  38.0      1      0  71.2833        C   First
2          1       3  female  26.0      0      0   7.9250        S   Third
3          1       1  female  35.0      1      0  53.1000        S   First
4          0       3    male  35.0      0      0   8.0500        S   Third
..       ...     ...     ...   ...    ...    ...      ...      ...     ...
95         0       3    male   NaN      0      0   8.0500        S   Third
96         0       1    male  71.0      0      0  34.6542        C   First
97         1       1    male  23.0      0      1  63.3583        C   First
98         1       2  female  34.0      0      1  23.0000        S  Second
99         0       2    male  34.0      1      0  26.0000        S  Second

      who  adult_male deck  embark_town alive  alone
0     man        True  NaN  Southampton    no  False
1   woman       False    C    Cherbourg   yes  False
2   woman       False  NaN  Southampton   yes   True
3   woman       False    C  Southampton   yes  False
4     man        True  NaN  Southampton    no   True
..    ...         ...  ...          ...   ...    ...
95    man        True  NaN  Southampton    no   True
96    man        True    A    Cherbourg    no   True
97    man        True    D    Cherbourg   yes  False
98  woman       False  NaN  Southampton   yes  False
99    man        True  NaN  Southampton    no  False

[100 rows x 15 columns]

In [101]:
dataset["age"].isna().any()

np.True_

In [102]:
dataset.dropna(inplace=True)

In [103]:
dataset["age"].isna().any()

np.False_

In [104]:
dataset.duplicated().sum()

np.int64(1)

In [105]:
dataset[dataset.duplicated(keep=False)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
369,1,1,female,24.0,0,0,69.3,C,First,woman,False,B,Cherbourg,yes,True
641,1,1,female,24.0,0,0,69.3,C,First,woman,False,B,Cherbourg,yes,True

In [106]:
dataset.drop_duplicates(inplace=True)

In [107]:
dataset.duplicated().sum()

np.int64(0)

In [108]:
dataset.drop(columns=["who","alone","adult_male"])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,deck,embark_town,alive
1,1,1,female,38.0,1,0,71.2833,C,First,C,Cherbourg,yes
3,1,1,female,35.0,1,0,53.1000,S,First,C,Southampton,yes
6,0,1,male,54.0,0,0,51.8625,S,First,E,Southampton,no
10,1,3,female,4.0,1,1,16.7000,S,Third,G,Southampton,yes
11,1,1,female,58.0,0,0,26.5500,S,First,C,Southampton,yes
...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,D,Southampton,yes
872,0,1,male,33.0,0,0,5.0000,S,First,B,Southampton,no
879,1,1,female,56.0,0,1,83.1583,C,First,C,Cherbourg,yes
887,1,1,female,19.0,0,0,30.0000,S,First,B,Southampton,yes
889,1,1,male,26.0,0,0,30.0000,C,First,C,Cherbourg,yes

In [109]:
dataset.dtypes

survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
deck           category
embark_town         str
alive               str
alone              bool
dtype: object

In [110]:
dataset["age"]=dataset["age"].astype(int)

In [111]:
dataset["alive"]

1      yes
3      yes
6       no
10     yes
11     yes
      ...
871    yes
872     no
879    yes
887    yes
889    yes
Name: alive, Length: 181, dtype: str

In [112]:
dataset.replace({'yes':1,'no':0,True:1,False:0},inplace=True)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38,1,0,71.2833,C,First,woman,0,C,Cherbourg,1,0
3,1,1,female,35,1,0,53.1000,S,First,woman,0,C,Southampton,1,0
6,0,1,male,54,0,0,51.8625,S,First,man,1,E,Southampton,0,1
10,1,3,female,4,1,1,16.7000,S,Third,child,0,G,Southampton,1,0
11,1,1,female,58,0,0,26.5500,S,First,woman,0,C,Southampton,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47,1,1,52.5542,S,First,woman,0,D,Southampton,1,0
872,0,1,male,33,0,0,5.0000,S,First,man,1,B,Southampton,0,1
879,1,1,female,56,0,1,83.1583,C,First,woman,0,C,Cherbourg,1,0
887,1,1,female,19,0,0,30.0000,S,First,woman,0,B,Southampton,1,1
889,1,1,male,26,0,0,30.0000,C,First,man,1,C,Cherbourg,1,1

In [113]:
dataset.drop(columns=["who","alone","adult_male"],inplace=True)
dataset.head(30)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,deck,embark_town,alive
1,1,1,female,38,1,0,71.2833,C,First,C,Cherbourg,1
3,1,1,female,35,1,0,53.1000,S,First,C,Southampton,1
6,0,1,male,54,0,0,51.8625,S,First,E,Southampton,0
10,1,3,female,4,1,1,16.7000,S,Third,G,Southampton,1
11,1,1,female,58,0,0,26.5500,S,First,C,Southampton,1
21,1,2,male,34,0,0,13.0000,S,Second,D,Southampton,1
23,1,1,male,28,0,0,35.5000,S,First,A,Southampton,1
27,0,1,male,19,3,2,263.0000,S,First,C,Southampton,0
52,1,1,female,49,1,0,76.7292,C,First,D,Cherbourg,1
54,0,1,male,65,0,1,61.9792,C,First,B,Cherbourg,0
62,0,1,male,45,1,0,83.4750,S,First,C,Southampton,0
66,1,2,female,29,0,0,10.5000,S,Second,F,Southampton,1
75,0,3,male,25,0,0,7.6500,S,Third,F,Southampton,0
88,1,1,female,23,3,2,263.0000,S,First,C,Southampton,1
92,0,1,male,46,1,0,61.1750,S,First,E,Southampton,0
96,0,1,male,71,0,0,34.6542,C,First,A,Cherbourg,0
97,1,1,male,23,0,1,63.3583,C,First,D,Cherbourg,1
102,0,1,male,21,0,1,77.2875,S,First,D,Southampton,0
110,0,1,male,47,0,0,52.0000,S,First,C,Southampton,0
118,0,1,male,24,0,1,247.5208,C,First,B,Cherbourg,0
123,1,2,female,32,0,0,13.0000,S,Second,E,Southampton,1
124,0,1,male,54,0,1,77.2875,S,First,D,Southampton,0
136,1,1,female,19,0,2,26.2833,S,First,D,Southampton,1
137,0,1,male,37,1,0,53.1000,S,First,C,Southampton,0
139,0,1,male,24,0,0,79.2000,C,First,B,Cherbourg,0
148,0,2,male,36,0,2,26.0000,S,Second,F,Southampton,0
151,1,1,female,22,1,0,66.6000,S,First,C,Southampton,1
170,0,1,male,61,0,0,33.5000,S,First,B,Southampton,0
174,0,1,male,56,0,0,30.6958,C,First,A,Cherbourg,0
177,0,1,female,50,0,0,28.7125,C,First,C,Cherbourg,0

In [114]:
dataset.drop(columns=["embarked"],inplace=True)

In [115]:
dataset.head(25)

,survived,pclass,sex,age,sibsp,parch,fare,class,deck,embark_town,alive
1,1,1,female,38,1,0,71.2833,First,C,Cherbourg,1
3,1,1,female,35,1,0,53.1000,First,C,Southampton,1
6,0,1,male,54,0,0,51.8625,First,E,Southampton,0
10,1,3,female,4,1,1,16.7000,Third,G,Southampton,1
11,1,1,female,58,0,0,26.5500,First,C,Southampton,1
21,1,2,male,34,0,0,13.0000,Second,D,Southampton,1
23,1,1,male,28,0,0,35.5000,First,A,Southampton,1
27,0,1,male,19,3,2,263.0000,First,C,Southampton,0
52,1,1,female,49,1,0,76.7292,First,D,Cherbourg,1
54,0,1,male,65,0,1,61.9792,First,B,Cherbourg,0
62,0,1,male,45,1,0,83.4750,First,C,Southampton,0
66,1,2,female,29,0,0,10.5000,Second,F,Southampton,1
75,0,3,male,25,0,0,7.6500,Third,F,Southampton,0
88,1,1,female,23,3,2,263.0000,First,C,Southampton,1
92,0,1,male,46,1,0,61.1750,First,E,Southampton,0
96,0,1,male,71,0,0,34.6542,First,A,Cherbourg,0
97,1,1,male,23,0,1,63.3583,First,D,Cherbourg,1
102,0,1,male,21,0,1,77.2875,First,D,Southampton,0
110,0,1,male,47,0,0,52.0000,First,C,Southampton,0
118,0,1,male,24,0,1,247.5208,First,B,Cherbourg,0
123,1,2,female,32,0,0,13.0000,Second,E,Southampton,1
124,0,1,male,54,0,1,77.2875,First,D,Southampton,0
136,1,1,female,19,0,2,26.2833,First,D,Southampton,1
137,0,1,male,37,1,0,53.1000,First,C,Southampton,0
139,0,1,male,24,0,0,79.2000,First,B,Cherbourg,0

In [116]:
dataset.rename(columns={'sibsp':'siblings_spouse','parch':'parents_children'},inplace=True)

In [117]:
dataset.head(50)

,survived,pclass,sex,age,siblings_spouse,parents_children,fare,class,deck,embark_town,alive
1,1,1,female,38,1,0,71.2833,First,C,Cherbourg,1
3,1,1,female,35,1,0,53.1000,First,C,Southampton,1
6,0,1,male,54,0,0,51.8625,First,E,Southampton,0
10,1,3,female,4,1,1,16.7000,Third,G,Southampton,1
11,1,1,female,58,0,0,26.5500,First,C,Southampton,1
21,1,2,male,34,0,0,13.0000,Second,D,Southampton,1
23,1,1,male,28,0,0,35.5000,First,A,Southampton,1
27,0,1,male,19,3,2,263.0000,First,C,Southampton,0
52,1,1,female,49,1,0,76.7292,First,D,Cherbourg,1
54,0,1,male,65,0,1,61.9792,First,B,Cherbourg,0
62,0,1,male,45,1,0,83.4750,First,C,Southampton,0
66,1,2,female,29,0,0,10.5000,Second,F,Southampton,1
75,0,3,male,25,0,0,7.6500,Third,F,Southampton,0
88,1,1,female,23,3,2,263.0000,First,C,Southampton,1
92,0,1,male,46,1,0,61.1750,First,E,Southampton,0
96,0,1,male,71,0,0,34.6542,First,A,Cherbourg,0
97,1,1,male,23,0,1,63.3583,First,D,Cherbourg,1
102,0,1,male,21,0,1,77.2875,First,D,Southampton,0
110,0,1,male,47,0,0,52.0000,First,C,Southampton,0
118,0,1,male,24,0,1,247.5208,First,B,Cherbourg,0
123,1,2,female,32,0,0,13.0000,Second,E,Southampton,1
124,0,1,male,54,0,1,77.2875,First,D,Southampton,0
136,1,1,female,19,0,2,26.2833,First,D,Southampton,1
137,0,1,male,37,1,0,53.1000,First,C,Southampton,0
139,0,1,male,24,0,0,79.2000,First,B,Cherbourg,0
148,0,2,male,36,0,2,26.0000,Second,F,Southampton,0
151,1,1,female,22,1,0,66.6000,First,C,Southampton,1
170,0,1,male,61,0,0,33.5000,First,B,Southampton,0
174,0,1,male,56,0,0,30.6958,First,A,Cherbourg,0
177,0,1,female,50,0,0,28.7125,First,C,Cherbourg,0
183,1,2,male,1,2,1,39.0000,Second,F,Southampton,1
193,1,2,male,3,1,1,26.0000,Second,F,Southampton,1
194,1,1,female,44,0,0,27.7208,First,B,Cherbourg,1
195,1,1,female,58,0,0,146.5208,First,B,Cherbourg,1
205,0,3,female,2,0,1,10.4625,Third,G,Southampton,0
209,1,1,male,40,0,0,31.0000,First,A,Cherbourg,1
215,1,1,female,31,1,0,113.2750,First,D,Cherbourg,1
218,1,1,female,32,0,0,76.2917,First,D,Cherbourg,1
224,1,1,male,38,1,0,90.0000,First,C,Southampton,1
230,1,1,female,35,1,0,83.4750,First,C,Southampton,1
245,0,1,male,44,2,0,90.0000,First,C,Queenstown,0
248,1,1,male,37,1,1,52.5542,First,D,Southampton,1
251,0,3,female,29,1,1,10.4625,Third,G,Southampton,0
252,0,1,male,62,0,0,26.5500,First,C,Southampton,0
257,1,1,female,30,0,0,86.5000,First,B,Southampton,1
262,0,1,male,52,1,1,79.6500,First,E,Southampton,0
263,0,1,male,40,0,0,0.0000,First,B,Southampton,0
268,1,1,female,58,0,1,153.4625,First,C,Southampton,1
269,1,1,female,35,0,0,135.6333,First,C,Southampton,1
273,0,1,male,37,0,1,29.7000,First,C,Cherbourg,0

In [118]:
dataset=pd.get_dummies(dataset,columns=["embark_town"],drop_first=True)

In [119]:
dataset.head(15)

,survived,pclass,sex,age,siblings_spouse,parents_children,fare,class,deck,alive,embark_town_Queenstown,embark_town_Southampton
1,1,1,female,38,1,0,71.2833,First,C,1,False,False
3,1,1,female,35,1,0,53.1000,First,C,1,False,True
6,0,1,male,54,0,0,51.8625,First,E,0,False,True
10,1,3,female,4,1,1,16.7000,Third,G,1,False,True
11,1,1,female,58,0,0,26.5500,First,C,1,False,True
21,1,2,male,34,0,0,13.0000,Second,D,1,False,True
23,1,1,male,28,0,0,35.5000,First,A,1,False,True
27,0,1,male,19,3,2,263.0000,First,C,0,False,True
52,1,1,female,49,1,0,76.7292,First,D,1,False,False
54,0,1,male,65,0,1,61.9792,First,B,0,False,False
62,0,1,male,45,1,0,83.4750,First,C,0,False,True
66,1,2,female,29,0,0,10.5000,Second,F,1,False,True
75,0,3,male,25,0,0,7.6500,Third,F,0,False,True
88,1,1,female,23,3,2,263.0000,First,C,1,False,True
92,0,1,male,46,1,0,61.1750,First,E,0,False,True

In [120]:
dataset["age"]=(dataset["age"]-dataset["age"].min())/(dataset["age"].max()-dataset["age"].min())

In [121]:
dataset.head(10)

,survived,pclass,sex,age,siblings_spouse,parents_children,fare,class,deck,alive,embark_town_Queenstown,embark_town_Southampton
1,1,1,female,0.4750,1,0,71.2833,First,C,1,False,False
3,1,1,female,0.4375,1,0,53.1000,First,C,1,False,True
6,0,1,male,0.6750,0,0,51.8625,First,E,0,False,True
10,1,3,female,0.0500,1,1,16.7000,Third,G,1,False,True
11,1,1,female,0.7250,0,0,26.5500,First,C,1,False,True
21,1,2,male,0.4250,0,0,13.0000,Second,D,1,False,True
23,1,1,male,0.3500,0,0,35.5000,First,A,1,False,True
27,0,1,male,0.2375,3,2,263.0000,First,C,0,False,True
52,1,1,female,0.6125,1,0,76.7292,First,D,1,False,False
54,0,1,male,0.8125,0,1,61.9792,First,B,0,False,False

In [122]:
dataset.drop(columns=["class"],inplace=True)

In [123]:
dataset.head(10)

,survived,pclass,sex,age,siblings_spouse,parents_children,fare,deck,alive,embark_town_Queenstown,embark_town_Southampton
1,1,1,female,0.4750,1,0,71.2833,C,1,False,False
3,1,1,female,0.4375,1,0,53.1000,C,1,False,True
6,0,1,male,0.6750,0,0,51.8625,E,0,False,True
10,1,3,female,0.0500,1,1,16.7000,G,1,False,True
11,1,1,female,0.7250,0,0,26.5500,C,1,False,True
21,1,2,male,0.4250,0,0,13.0000,D,1,False,True
23,1,1,male,0.3500,0,0,35.5000,A,1,False,True
27,0,1,male,0.2375,3,2,263.0000,C,0,False,True
52,1,1,female,0.6125,1,0,76.7292,D,1,False,False
54,0,1,male,0.8125,0,1,61.9792,B,0,False,False

In [124]:
dataset["fare"]=(dataset["fare"]-dataset["fare"].min())/(dataset["fare"].max()-dataset["fare"].min())

In [125]:
dataset.head(10)

,survived,pclass,sex,age,siblings_spouse,parents_children,fare,deck,alive,embark_town_Queenstown,embark_town_Southampton
1,1,1,female,0.4750,1,0,0.139136,C,1,False,False
3,1,1,female,0.4375,1,0,0.103644,C,1,False,True
6,0,1,male,0.6750,0,0,0.101229,E,0,False,True
10,1,3,female,0.0500,1,1,0.032596,G,1,False,True
11,1,1,female,0.7250,0,0,0.051822,C,1,False,True
21,1,2,male,0.4250,0,0,0.025374,D,1,False,True
23,1,1,male,0.3500,0,0,0.069291,A,1,False,True
27,0,1,male,0.2375,3,2,0.513342,C,0,False,True
52,1,1,female,0.6125,1,0,0.149765,D,1,False,False
54,0,1,male,0.8125,0,1,0.120975,B,0,False,False

In [126]:
dataset['sex']=dataset['sex'].map({"female":0,"male":1})

In [127]:
dataset=pd.get_dummies(dataset,columns=["deck"],drop_first=True)

In [128]:
dataset.drop(columns=["alive"],inplace=True)

In [129]:
dataset.head(15)

,survived,pclass,sex,age,siblings_spouse,parents_children,fare,embark_town_Queenstown,embark_town_Southampton,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G
1,1,1,0,0.4750,1,0,0.139136,False,False,False,True,False,False,False,False
3,1,1,0,0.4375,1,0,0.103644,False,True,False,True,False,False,False,False
6,0,1,1,0.6750,0,0,0.101229,False,True,False,False,False,True,False,False
10,1,3,0,0.0500,1,1,0.032596,False,True,False,False,False,False,False,True
11,1,1,0,0.7250,0,0,0.051822,False,True,False,True,False,False,False,False
21,1,2,1,0.4250,0,0,0.025374,False,True,False,False,True,False,False,False
23,1,1,1,0.3500,0,0,0.069291,False,True,False,False,False,False,False,False
27,0,1,1,0.2375,3,2,0.513342,False,True,False,True,False,False,False,False
52,1,1,0,0.6125,1,0,0.149765,False,False,False,False,True,False,False,False
54,0,1,1,0.8125,0,1,0.120975,False,False,True,False,False,False,False,False
62,0,1,1,0.5625,1,0,0.162932,False,True,False,True,False,False,False,False
66,1,2,0,0.3625,0,0,0.020495,False,True,False,False,False,False,True,False
75,0,3,1,0.3125,0,0,0.014932,False,True,False,False,False,False,True,False
88,1,1,0,0.2875,3,2,0.513342,False,True,False,True,False,False,False,False
92,0,1,1,0.5750,1,0,0.119406,False,True,False,False,False,True,False,False

In [130]:
dataset = pd.get_dummies(dataset, columns=["pclass"], drop_first=True)

In [131]:
dataset["family_size"]=dataset["siblings_spouse"]+dataset["parents_children"]

In [132]:
dataset.head(20)

,survived,sex,age,siblings_spouse,parents_children,fare,embark_town_Queenstown,embark_town_Southampton,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,pclass_2,pclass_3,family_size
1,1,0,0.4750,1,0,0.139136,False,False,False,True,False,False,False,False,False,False,1
3,1,0,0.4375,1,0,0.103644,False,True,False,True,False,False,False,False,False,False,1
6,0,1,0.6750,0,0,0.101229,False,True,False,False,False,True,False,False,False,False,0
10,1,0,0.0500,1,1,0.032596,False,True,False,False,False,False,False,True,False,True,2
11,1,0,0.7250,0,0,0.051822,False,True,False,True,False,False,False,False,False,False,0
21,1,1,0.4250,0,0,0.025374,False,True,False,False,True,False,False,False,True,False,0
23,1,1,0.3500,0,0,0.069291,False,True,False,False,False,False,False,False,False,False,0
27,0,1,0.2375,3,2,0.513342,False,True,False,True,False,False,False,False,False,False,5
52,1,0,0.6125,1,0,0.149765,False,False,False,False,True,False,False,False,False,False,1
54,0,1,0.8125,0,1,0.120975,False,False,True,False,False,False,False,False,False,False,1
62,0,1,0.5625,1,0,0.162932,False,True,False,True,False,False,False,False,False,False,1
66,1,0,0.3625,0,0,0.020495,False,True,False,False,False,False,True,False,True,False,0
75,0,1,0.3125,0,0,0.014932,False,True,False,False,False,False,True,False,False,True,0
88,1,0,0.2875,3,2,0.513342,False,True,False,True,False,False,False,False,False,False,5
92,0,1,0.5750,1,0,0.119406,False,True,False,False,False,True,False,False,False,False,1
96,0,1,0.8875,0,0,0.067640,False,False,False,False,False,False,False,False,False,False,0
97,1,1,0.2875,0,1,0.123667,False,False,False,False,True,False,False,False,False,False,1
102,0,1,0.2625,0,1,0.150855,False,True,False,False,True,False,False,False,False,False,1
110,0,1,0.5875,0,0,0.101497,False,True,False,True,False,False,False,False,False,False,0
118,0,1,0.3000,0,1,0.483128,False,False,True,False,False,False,False,False,False,False,1

In [137]:
dataset.drop(columns=["siblings_spouse","parents_children"],inplace=True)

In [138]:
dataset.head(20)

,survived,sex,age,fare,embark_town_Queenstown,embark_town_Southampton,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,pclass_2,pclass_3,family_size
1,1,0,0.4750,0.139136,False,False,False,True,False,False,False,False,False,False,1
3,1,0,0.4375,0.103644,False,True,False,True,False,False,False,False,False,False,1
6,0,1,0.6750,0.101229,False,True,False,False,False,True,False,False,False,False,0
10,1,0,0.0500,0.032596,False,True,False,False,False,False,False,True,False,True,2
11,1,0,0.7250,0.051822,False,True,False,True,False,False,False,False,False,False,0
21,1,1,0.4250,0.025374,False,True,False,False,True,False,False,False,True,False,0
23,1,1,0.3500,0.069291,False,True,False,False,False,False,False,False,False,False,0
27,0,1,0.2375,0.513342,False,True,False,True,False,False,False,False,False,False,5
52,1,0,0.6125,0.149765,False,False,False,False,True,False,False,False,False,False,1
54,0,1,0.8125,0.120975,False,False,True,False,False,False,False,False,False,False,1
62,0,1,0.5625,0.162932,False,True,False,True,False,False,False,False,False,False,1
66,1,0,0.3625,0.020495,False,True,False,False,False,False,True,False,True,False,0
75,0,1,0.3125,0.014932,False,True,False,False,False,False,True,False,False,True,0
88,1,0,0.2875,0.513342,False,True,False,True,False,False,False,False,False,False,5
92,0,1,0.5750,0.119406,False,True,False,False,False,True,False,False,False,False,1
96,0,1,0.8875,0.067640,False,False,False,False,False,False,False,False,False,False,0
97,1,1,0.2875,0.123667,False,False,False,False,True,False,False,False,False,False,1
102,0,1,0.2625,0.150855,False,True,False,False,True,False,False,False,False,False,1
110,0,1,0.5875,0.101497,False,True,False,True,False,False,False,False,False,False,0
118,0,1,0.3000,0.483128,False,False,True,False,False,False,False,False,False,False,1